---
name: cd

concurrency:
    group: ${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the container image
        uses: ansible/ansible-workspace-env-reference-image/.github/actions/build-release@main
        with:
          publish: 'true'
